### PR TITLE
top -> xvi-ee

### PR DESCRIPTION
**Pull request by speleo3**
PocketTopo -> XVI extended elevation dump with `topreader.py --dump xvi-ee`

Note: Splay direction is not yet handled, they are <del>always placed in forward direction</del> <ins>skipped for now</ins>.

Closes https://github.com/speleo3/inkscape-speleo/issues/14

### CODE REVIEW

**Comment by speleo3** [comment]
@MFeldmaier can you please review?

**Comment by MFeldmaier** [comment]
Looks good.

One minor remark.

When I  call the `-h` option on `topreader.py`

```
fem@rechner:~/Hoefo/inkscape-speleo/extensions$ ./topreader.py -h
usage: topreader.py [-h] [--dump {json,svg,svx,th,th2,tro,xvi,xvi-ee,th2-xvi}] [--view {aven,inkscape}] [--surveyname SURVEYNAME] [--prefixadd PREFIXADD] [--prefixstrip PREFIXSTRIP] [--no-avg] [--do-sep] FILENAME [FILENAME ...]

positional arguments:
  FILENAME              one or more .top files

options:
  -h, --help            show this help message and exit
  --dump {json,svg,svx,th,th2,tro,xvi,xvi-ee,th2-xvi}
                        dump file to stdout
  --view {aven,inkscape}
                        open viewer application
  --surveyname SURVEYNAME
                        survey name for survex dump
  --prefixadd PREFIXADD
                        station name prefix to add
  --prefixstrip PREFIXSTRIP
                        station name prefix to strip
  --no-avg              don't average repeated legs
  --do-sep              separate legs from splays
  ```

the explanation is rather short.
Could you improve the help menu and add some explanation to the individual options.

I especially found the difference between `xvi` and `xvi-ee` not self-explaining.
Maybe rename the first to `xvi-plan`?

Anyway, just a suggestion ;-)

**Review by MFeldmaier — APPROVED** [review]
Looks good, thanks!

**Comment by speleo3** [comment]
Thanks @MFeldmaier, I moved your feedback to a new ticket: https://github.com/speleo3/inkscape-speleo/issues/21

**Pull request merged**
