### PR TITLE
Station name parsing robust

### PR DESCRIPTION
**Pull request by rsevero**
Station name parsing should be more robust as current code creates stations H8. H9. HA, HB, etc from starting base H8.

It also forces letters capitalization.

These changes fixes both issues amking more complex station names also supported.

### CODE REVIEW

**Comment by speleo3** [comment]
I recently added the first tests to this repo (see https://github.com/speleo3/inkscape-speleo/tree/master/tests ). There are no tests for `th2enumeratestations.py` yet. Do you think you could add tests for `StationName` and `SeparateStationNameParts`?

**Comment by rsevero** [comment]
> I recently added the first tests to this repo (see https://github.com/speleo3/inkscape-speleo/tree/master/tests ). There are no tests for `th2enumeratestations.py` yet. Do you think you could add tests for `StationName` and `SeparateStationNameParts`?

Yes. I will do it tomorrow.

**Comment by speleo3** [comment]
Hi @rsevero - Any progress with the tests? Can I help you with that?

**Comment by rsevero** [comment]
I am coming back from a cave expedition now.

I will try to take a look at this issue this week.

Regards,

Rodrigo

-------- Mensagem Original --------
Em 4 de fev. de 2024, 08:49, Thomas Holder escreveu:

**Comment by rsevero** [comment]
The tests as requested.

**Comment by speleo3** [comment]
> The tests as requested.

Perfect, thank you so much!

**Pull request merged**
